apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-headless
  namespace: {{ include "haproxy-redis.namespace" . }}
  labels:
    {{- include "haproxy-redis.labels" . | nindent 4 }}
    {{- include "haproxy-redis.redis.selectorLabels" . | nindent 4 }}
  {{- with .Values.redis.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "haproxy-redis.redis.selectorLabels" . | nindent 4 }}
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
