{{- if and .Values.redis.auth.enabled (not .Values.redis.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "haproxy-redis.authSecretName" . }}
  namespace: {{ include "haproxy-redis.namespace" . }}
  labels:
    {{- include "haproxy-redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.redis.auth.password | required "redis.auth.password is required when auth.enabled=true and no existingSecret is set" | quote }}
{{- end }}
