apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "filebrowser.fullname" . }}
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "filebrowser.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "filebrowser.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: database
              mountPath: /database
            - name: data
              mountPath: /srv
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "filebrowser.fullname" . }}-config
        - name: database
          persistentVolumeClaim:
            claimName: {{ include "filebrowser.fullname" . }}-database
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingClaim }}
