apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}-config
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}-database
  labels:
    {{- include "filebrowser.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.database.size }}
